# Generated by Django 4.0.2 on 2022-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportowiec',
            name='rok',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportowiec',
            name='imie',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sportowiec',
            name='nazwisko',
            field=models.CharField(max_length=20),
        ),
    ]
