# Generated by Django 4.0.2 on 2022-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sportowiec_rok_alter_sportowiec_imie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportowiec',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sportowiec',
            name='zdjęcie',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia'),
        ),
    ]
